### ISSUE TITLE
Chart doesn't respect container's width

### ISSUE THREAD

**Issue by alexisagos** [highcharts/highcharts-vue#107]
Hi, I'm using highcharts inside tabs from Element UI framework and on first load the chart is always exceeding the parent container. How can I fix this ?

I have reproduced the problem here:
https://codepen.io/AlexisSK/pen/XQJKMW

**Comment by Denyllon** [comment]
Hello @alexisagos ,

The problem occurs because you are rendering a Chart component  inside of another component, but its dimensions strictly depends on the parent component which is actually not already mounted while the chart is rendering.
The easiest way to fix it would be to use `v-if` on the chart component and render it only when rendering the parent component has finished.

Here is the example which shows how it could be fixed: https://jsfiddle.net/BlackLabel/nhek71tx/

Kind regards!

**Comment by alexisagos** [comment]
Hi Denyllon,
Thanks for your quick response, I had tried this and I thought it wasn't working because when developing locally, the bug remained sometimes. When deployed, it is fixed. I believe it is something to do with how webpack serves assets in development mode that made the styles trigger in the wrong order or something..

**Comment by Denyllon** [comment]
Thank you for letting me know. Anyway, I recommend you to apply the above solution, because it generally prevents the vast majority of problems with rendering DOM elements order.
