### ISSUE TITLE
How to map series data into table?

### ISSUE THREAD

**Issue by cyberfly** [highcharts/highcharts-vue#109]
Hi using Highcharts Vue, is it possible to auto mapped the series data into a table? Or do I manually build the table row using v-for?

In short:

1. I have series data
2. I want to convert the series data into Chart and Table (Chart part is working correctly)

Example below

![image](https://user-images.githubusercontent.com/1756170/65818591-741a1d00-e245-11e9-8a96-3908d8b4a9a5.png)

Thanks

**Comment by Denyllon** [comment]
Hi @cyberfly,

Thank you for asking question.
You can import the `export-data.js` Highcharts module in order to generate and show the table with data. After including this module, just need to click hamburger menu button at the top right corner, and select the `View data table`. Then the table will appear below your chart.
Of course you can style the table whatever you want.

Live example: https://codesandbox.io/s/highcharts-vue-demo-pj8uk

Kind regards!
