### ISSUE TITLE
Access vue function from event defined in Highcharts

### ISSUE THREAD

**Issue by greenertux** [highcharts/highcharts-vue#110]
I have created a chart that is loaded like this in my template:
highcharts :options="chart2" />

The options are declared like this:
data () {
    return {
      chart2: { chart: { type: 'pie', backgroundColor: 'lightblue' }, title: { text: '' }, plotOptions: { pie: { allowPointSelect: true, cursor: 'pointer', showInLegend: true, dataLabels: { enabled: false } }, series: { point: { events: { click: this.docList(this.name) } } } }, series: [] }
    }

The chart works fine and the click event handler function is called. However I cannot find a way to call a function defined in vue. It seems the Highcharts code is native JS that has no connection to the Vue objects. Do you have an idea how to access vue functions?

**Comment by Denyllon** [comment]
Hi @greenertux ,

Thank you for asking question.
It does not work because, as you should know the `this` keyword within function indicates the element on which a function was called. In this case engine is searching for `docList` function on the `Point` class object on which the click event handler was called.
In order to make it works, you should use the [Arrow Function](https://www.w3schools.com/js/js_arrow_function.asp), where the `this` keyword always represents the object that defined the arrow function.

Live example: https://codesandbox.io/s/highcharts-vue-demo-fdtpp

Kind regards!

**Comment by greenertux** [comment]
Thanks it indeed works, but using the arrow function I can no longer access the highcharts object that was clicked. Is there a way do do this?

**Comment by Denyllon** [comment]
You did not mention before about referring both of Point and Vue's component object within the same function, that's why I've suggested to use arrow function. However, you can also access the Point object through event passed to the arrow function, like in the example below.

Live example: https://codesandbox.io/s/highcharts-vue-demo-8ef6t
API Reference: https://api.highcharts.com/highcharts/series.line.point.events.click

> Fires when a point is clicked. One parameter, event, is passed to the function, containing common event information.

Kind regards!

**Comment by Denyllon** [comment]
> but it seems it does not provide a way to figure out which element of the series was clicked.
Actually it is, and that's the Point object which I mentioned in the last message. Please open my example, click on some point, and open the console. There you can find a specific point which was clicked.
If you would like to access series of the clicked point, it's also available on Point object, by referring `event.point.series` within function.

Live example: https://codesandbox.io/s/highcharts-vue-demo-6csfp

Hope it helps, but if is there something what I do not clearly understand, please try to explain it more precisely.

Kind regards!
