### ISSUE TITLE
how to add indicator chart from a different component 

### ISSUE THREAD

**Issue by gautammedhi** [highcharts/highcharts-vue#112]
I have a stock chart in chart.vue. I want to dynamically add indicators linked to this chart in a different component indicators.vue. Is there any way to call the indicator series in this new component

**Comment by Denyllon** [comment]
Hi @gautammedhi ,

Thank you for asking question.
If you have a lot of Chart instances, they're running the same Highcharts library either way (I assume you did not pass the different Highcharts instance through the `:highcharts` wrapper property), so you can load every required indicator once in your global Chart component, as every other Highcharts module. Then it will be available from all components which uses the same Highcharts instance.

If you would have any doubts, further questions or encounter any issue, please let me know.

Kind regards!

**Comment by gautammedhi** [comment]
I am facing a lot of problem while developing highcharts. First of all I
use highcharts-vue and vuetify. I have a drop down to add indicators
dynamically. Upto this it was fine within a same component. But I want to
use some vuetify/ bootstrap element in the indicator chart. For that I want
another component. Because I dont think there's anything like rendering a
volume up/down kind of slider inside highcharts area.
Let me give you an example. Have you ever gone through tradingview.com.
They used some html elements inside the 'indicator' chart area. so when I
select dropdown option, a new indicator should be created with a slider and
menu bar above it.

**Comment by gautammedhi** [comment]
Thank you so much for the response . I am in great trouble. I have been
trying since 2 days.

**Comment by gautammedhi** [comment]
my design is given in the screenshot

**Comment by Denyllon** [comment]
> Have you ever gone through tradingview.com.
They used some html elements inside the 'indicator' chart area. so when I
select dropdown option, a new indicator should be created with a slider and
menu bar above it.

I think that question should be redirected to Highcharts support, because it is not directly applicable to a wrapper library, but actually to a native Highcharts.

Regarding adding (loading) indicators, the case looks like I wrote above. You just need to load a required indicators modules once (for example in your `App.vue` file). After that, they should be available globally, and will be able to apply to a chart, by defining the new series. Please take a look on the example below.

Live demo: https://codesandbox.io/s/highcharts-vue-demo-g8640

Kind regards!
