### ISSUE TITLE
Js fiddle not working on readme.md

### ISSUE THREAD

**Issue by Renato66** [highcharts/highcharts-vue#115]
Js fiddle not working on readme.md
https://github.com/highcharts/highcharts-vue/blame/master/README.md#L68

**Comment by Denyllon** [comment]
Hi @Renato66 ,

The problem is caused by the fact that the RAWGit platform which provides a minified version of wrapper package, is no longer available. We needed to find new CDN for our package, and change it in the example. Now the example is fixed and should work properly.

Really appreciate your report!
Kind regards.
