### ISSUE TITLE
chartOptions.plotOptions.series.pointStart is not reactive

### ISSUE THREAD

**Issue by Renato66** [highcharts/highcharts-vue#125]
I`ve expected that only changing:
`chartOptions.plotOptions.series.pointStart = somevalue` 
would work, but i need to redraw the chart to work
example in this [fiddle](https://jsfiddle.net/7t6qnvoh/2/)

**Comment by Denyllon** [comment]
Hello @Renato66 ,

Thank you for contacting us.
The problem is reproduced also with native library. This package only wraps the Highcharts and creates some kind of new Vue component, so the above issue should definitely be reported directly on the library's repository.

Here is the example which does not use Vue at all, where you can observe that the problem is also noticeable.
https://jsfiddle.net/BlackLabel/va4xomds/

Kind regards!
