### ISSUE TITLE
Does the highcharts-vue support customized lang.noData?

### ISSUE THREAD

**Issue by CathyQin** [highcharts/highcharts-vue#128]
I have involved the following requirement in my project, `require('highcharts/modules/no-data-to-display.js')(Highcharts);`. And then, the default message has been displayed. I tried to change the default value of lang.noData, however, the default value cannot be changed.
Is there any possible way to change the value?
Thanks~

**Comment by Denyllon** [comment]
Hi @CathyQin ,

Thank you for reporting the issue.
Without any closer look on your code , I can only guess that you're trying to set `lang.noData` directly through the chart configuration, but all those options should be set globally by passing configuration object into the `Highcharts.setOptions()` method. Please take a look on the example below. I hope it will help you to resolve your problems.

By the way, apologize for a bit of late in reply. It was caused by winter holidays in a christmas time.

Live example: https://codesandbox.io/s/highcharts-vue-demo-lbubk
API Reference: https://api.highcharts.com/highcharts/lang

Kind regards!
