### ISSUE TITLE
What's the correct usage with TypeScript

### ISSUE THREAD

**Issue by jonny7** [highcharts/highcharts-vue#130]
Hi

Just getting started with Highcharts, which I've used a lot, but first time using it with Vue and in particular TypeScript + Vue. Just wondering of the correct way to use it. As an example, I can't build a project due to this line
```typescript
 yAxis: {
        labels: {
          formatter: function() {
            let labels = Statuses.map(status => status.status);
            let current: number = this.value; // --> this.value => Property 'value' does not exist on type '{ step: number; formatter: () => string; }
            return labels[current];
          }
        }
}
```
I'm using a computed method to return the chart. On a related note, what is the correct way to reference the Highcharts `this` and the Vue `this` from within methods/computed props/life-cycle hooks? I'm assuming something like `var ctx = this;` inside the method that returns the chart, but wanted to check

**Comment by Denyllon** [comment]
Hi @jonny7 ,

Thank you for asking question. I think that the fastest way to achieve the expected effect would be to define additional variable e.g called `ctx`, right before component's `export` statement, and then assign `this` to the mentioned variable, within `beforeCreate()` lifecycle hook.
After that you will be able to refer `this` as context of formatter function, and also a component itself.
Please take a look on that example: https://codesandbox.io/s/highcharts-vue-demo-olp24

Kind regards!

**Comment by jonny7** [comment]
Hi @Denyllon 

Thanks for the reply, I think maybe I miscommunication my problem. I can access the `formatter` context and the `Vue` context fine, I used a similar approach to your answer and will post my code in it's entirety here for the computed property with Typescript.

```TypeScript
  get performanceTimeline() {
    var ctx = this;
    return {
      rangeSelector: {
        selected: 1
      },
      title: {
        text: "Performance Over Time"
      },
      yAxis: {
        labels: {
          formatter: function(): string {
            let labels = Statuses.map(status => status.status);
            let current: number = this.value; // Error 1
            return labels[current];
          }
        }
      },
      tooltip: {
        formatter: function(): string {
          return "<b>Status:</b> " + ctx.mapTestStatus(this.y); // Error 2
        }
      },
      series: [
        {
          name: "Status",
          step: true,
          data: this.latestRsults.map(test => {
            return [test.created_on * 1000, test.status_id];
          }),
          pointStart: Date.UTC(2018, 1, 1),
          pointInterval: 1000 * 3600 * 24
        }
      ]
    };
  }
```

My problem is that TypeScript will not build the project, even though it works as expected in the browser. When I run `npm run build` it gives me errors of
Error 1: `Property 'value' does not exist on type '{ formatter: () => string; }'.`
and
Error 2:`Property 'y' does not exist on type '{ formatter: () => string; }'.`

I also did change my ctx var to the way you suggested and I ended up with the same Typescript error. So am I misunderstanding your first answer?

**Comment by Denyllon** [comment]
Thank you for explanation. Could you provide me with minimal example, where the problem occurs?
You can simply start implementing it from here: https://codesandbox.io/s/highcharts-vue-demo-om3ri

Kind regards!

**Comment by jonny7** [comment]
Hi @Denyllon 

I had some trouble using codesandbox, but I've provided a repo with the minimal reproducible error https://github.com/jonny7/ts-highcharts. It will display the image fine
![image](https://user-images.githubusercontent.com/6732997/73379966-98404600-4299-11ea-86c3-b35af7248c11.png)

but if you run `npm run build` it will fail with the mentioned errors above.
![image](https://user-images.githubusercontent.com/6732997/73380096-d0478900-4299-11ea-82b1-fe14bd7edc6f.png)

**Comment by Denyllon** [comment]
Hi @jonny7 ,

I've just took a look on your repository's code, and found solutions for all of your problems.
First of all, those errors are caused by the fact, that types for `this` context are not specified at all within your function definitions.

In order to get rid of them, you just need to define the types of particular things in your code, namely:
- chart options - by assigning the returned object from `performanceTimeline` getter into a variable (e.g called `chartConfig`), and then defining a type of that variable as `Highcharts.Options`.
- tooltip formatter function - here, you need to define a context type of that function only, as `Highcharts.TooltipFormatterContextObject`.
- yAxis labels formatter function - Setting a context type as well, but the different one: `Highcharts.AxisLabelsFormatterContextObject`

_Please note, that before those actions you need to import Highcharts package in `Home.vue` file, because you need to have an access (reference) to definitions._

After these steps, there will another problems appear. The `series` and `step` properties will be underlined, because when using TypeScript, we need to always define the type of every series within its config. Regarding the `step`, there is no such a way of configure it by assigning `true` value to it, so please chose one of available options (`'left'`, `'right'`, `'center'`).

If every above change will be applied, your code should look like below:
```vue
<template>
  <highcharts
    class="stock"
    :constructor-type="'stockChart'"
    :options="performanceTimeline"
  ></highcharts>
</template>

<script lang="ts">
import Vue from "vue";
import Highcharts from "highcharts";
import Component from "vue-class-component";

@Component
export default class OverTimeChart extends Vue {
  results: number[] = [1, 2, 3, 4, 5];

  get performanceTimeline() {
    let ctx = this,
      chartConfig: Highcharts.Options = {
        rangeSelector: {
          selected: 1
        },
        title: {
          text: "Performance Over Time"
        },
        yAxis: {
          labels: {
            formatter: function(
              this: Highcharts.AxisLabelsFormatterContextObject
            ): string {
              let labels = ["a", "b", "c", "d", "e"];
              let current: number = this.value;
              return labels[current];
            }
          }
        },
        tooltip: {
          formatter: function(
            this: Highcharts.TooltipFormatterContextObject
          ): string {
            return "<b>Status:</b> " + this.y;
          }
        },
        series: [
          {
            type: "line",
            name: "Status",
            step: "left",
            data: this.results.map(test => {
              return [1580315144 + 86000 * test * 1000, test];
            }),
            pointInterval: 1000 * 3600 * 24
          }
        ]
      };

    return chartConfig;
  }
}
</script>
```

**Comment by jonny7** [comment]
Hi @Denyllon 

Thanks very much for taking the time to help resolve the errors, this was really great! :slightly_smiling_face:
