### ISSUE TITLE
callback after redraw ? 

### ISSUE THREAD

**Issue by hounded** [highcharts/highcharts-vue#133]
hi, i'm using https://github.com/streamlinesocial/highcharts-regression

and i'm using `updateArgs="[true,false,{duration:500}]"` because highcharts-regression adds another series that being the regression line. Highcharts regression also has exposed properties of the added series https://github.com/streamlinesocial/highcharts-regression#exposed-properties which I would like to access namely the equation. However I can't seem to work out a way, even with a call back function `:callback="regressionProperties()"` that would then allow me to access the new added regression series. 

Am I doing something wrong here ?

**Comment by Denyllon** [comment]
Hi @hounded ,

First of all, I want to really apologize for not replying on your report. We've lost the tracking of this ticket for some reason, and that's why you did not receive any answer here. We're doing all the best to avoid similar situations, but unfortunately sometimes it's happening though.
Actually this topic is the typical support question, but here, we're handling the bug reports of the Highcharts Vue wrapper, and usually these kind of problems are forwarded by us to one of official support channels.
Well, given the fact that you've been waiting so long, for what I want to apologize again, we will try to help you here if you have not got rid of this problem. Could you tell me, do you still need some suport with this issue?

Kind regards!

**Comment by Denyllon** [comment]
Closed due to inactivity.
