### ISSUE TITLE
Adding and removing series

### ISSUE THREAD

**Issue by lukesaunders** [highcharts/highcharts-vue#140]
In my local code updating the series data structure can result in this error:

```
client.js:160 TypeError: d[r].update is not a function
    at k.eval (highcharts.js:369)
    at Array.forEach (<anonymous>)
    at k.updateData (highcharts.js:369)
    at k.setData (highcharts.js:371)
    at k.update (highcharts.js:429)
    at eval (highcharts.js:422)
    at Array.forEach (<anonymous>)
    at eval (highcharts.js:421)
    at Array.forEach (<anonymous>)
    at d.Chart.update (highcharts.js:421)
```

which comes from the `oldData[i].update` line from `updateData` in highcharts.js. It only happens when removing an existing series when all series items have ids, and I think only happens when the date axis has a min set. Hacking the code to set `updatePoints` to false also prevents the error, but there's no way to set this via highcharts-vue. The jsfiddle I made to reproduce doesn't give the error, but still shows a bug which I hope is related.

If you click 'break it' in this example, I'd expect the badgers item to be removed, the dogs item to be added and the squirrels item to remain. But you have to click it twice for this to happen - on the first click both existing series disappear: https://jsfiddle.net/fs12pq6z/2/ 

Is there some other way to remove a series and add another via highcharts-vue?

Update: here is a jsfiddle which does give a JS error, but it uses the JSONified chartOptions from my real data which are quite large. Expected result is that the item called "Ethereum" is removed and a new item called "Elrond" is added. https://jsfiddle.net/ug7na2bh/

**Comment by Denyllon** [comment]
Hi @lukesaunders ,

Thank you for reporting the issue.
Basically, this issue should be reported directly in Highcharts repository, instead of here, because the problem occurs even if not using the Highcharts Vue wrapper (natively).
I also made a quick investigation in this topic, and reported the bug directly in Highcharts.
Regarding the error thrown in console, you can avoid it by increasing `series.cropThreshold` value of all series, and changing the order of series passed into the `update`, so that the new series will be put into the place of series you need to remove.
I hope the following solution will help you until the fix will come out.

GitHub issue: https://github.com/highcharts/highcharts/issues/13541
Workaround: https://jsfiddle.net/BlackLabel/7yt3abxw/

Kind regards!

**Comment by lukesaunders** [comment]
@Denyllon since the underlying issue in highcharts has been open since 2018, can we not make highcharts-vue a bit smarter? Implementing something like #86 plus using `addSeries` for new series, and `remove()` removed series etc

I would be willing to do a PR for it. But tbh feels like there should be some discount on the library for that since this is a paid product.

**Comment by Denyllon** [comment]
@lukesaunders Thank you for agreeing with my enhancement suggestion. We have plans to improve it, but for now I'm not able to give you any ETA.
