### ISSUE TITLE
mouse scroll to zoom highstock data in vue

### ISSUE THREAD

**Issue by taufiknur** [highcharts/highcharts-vue#146]
hello plz, help me how to set mouse scroll to zoom highstock data in vue and load range data server, 
I found this demo but only for plain javascript, how to implement in vue

http://jsfiddle.net/w8nxu4e0/

**Comment by Denyllon** [comment]
Hi @taufiknur 

Thank you for opening the issue.
As it is possible to make the mouse wheel get to work on the chart with static data, that an attempt to do it with dynamic data (combination of loading data from server and using `mapNavigation` options) is not simply possible, because every time you would **zoom in** the chart, then the data extreme values are getting narrowed down, and zooming out doesn't work at all.

In order to make it work close to the effect you need, it is necessary to edit 'Chart.mapZoom' Highcharts core function, so that it will take the data max and min values from navigator, and set the redrawing interval manually. Please take a look on the example below.

Live example: https://codesandbox.io/s/highcharts-vue-demo-kh449
