### ISSUE TITLE
Changing axis of Solid Gauge resets chart to initial value

### ISSUE THREAD

**Issue by iamstevemckinney** [highcharts/highcharts-vue#159]
If I update the value of a solid gauge chart series and then later update the axis min or max I'm finding the chart refreshes and shows the initial value of the series. This seems to happen at highcharts-vue v1.3.2 but not on earlier versions. 

Example, https://codesandbox.io/s/highcharts-vue-demo-ishwp?fontsize=14&hidenavigation=1&theme=dark

Click "change value" and then "change y axis max". The value should still be 200, but it goes back to 500. If you lower the version of highcharte-vue to v1.3.1 the desired outcome will not function properly.

**Comment by Denyllon** [comment]
Hi @iamstevemckinney ,

Thank you for reporting the issue.
First of all, you should be aware that that the latest release is more polished, and work better that than older versions, and the problem stems from a wrong implementation, because you're updating the point directly on the chart instance (instead  of updating the data stored within your component), and then overriding it by the old configuration while setting extremes through changing component state.
It should be implemented like this: https://codesandbox.io/s/highcharts-vue-demo-forked-sigy7

Kind regards!

**Comment by iamstevemckinney** [comment]
Thank you for your response!

I actually started off doing it that way, but having the entire plot area refresh every time the value changes was undesirable to me. I found another issue, #28 where you had said updating the entire series was incorrect and each point should be updated directly. I'm assuming that is no longer correct and the issue of the plot area flashing/refreshing is perhaps still an issue?

**Comment by Denyllon** [comment]
@iamstevemckinney,
Really sorry for not answering, I've lost the tracking of this issue somehow.
Anyway, in the mentioned issue I was talking about the other version of wrapper which doesn't handle the data mutation of Highcharts, and kept that behaviour as it was originally in Highcharts. For now, the data mutation should be totally disabled through `deepCopyOnUpdate` property,  so the object passed to the chart update is a deep copy of configuration, instead of shallow only.

The problem that the plot area (actually, the `pane`) is animating every time, is related directly with Highcharts library, and should be reported within its repository excluding Vue wrapper usage.

In order to avoid the problem you found, you can manually update the chart with the `pane` options when mounted, but keep the other stuff inside of the component's data. Take a look on the example below:

Live example: https://codesandbox.io/s/highcharts-vue-demo-forked-id4qu?file=/src/App.vue

Kind regards!
