### ISSUE TITLE
Chart has trouble when changing number of items to display

### ISSUE THREAD

**Issue by dcavins** [highcharts/highcharts-vue#161]
Hi Vue wrapper developers,

Thanks for providing this wrapper for Highcharts elements. 

I have run into an issue with a chart that uses two sets of data that are of differing length. When you show the longer data, then switch back to the shorter set, the shorter set's data is translated out to fill the old number of positions. Here's an example: https://codepen.io/dcavins/pen/yLOGrqg
After the page loads, switch the chart's data (using the selector in the upper left corner) from "Shorter" to "Longer." Then switch it back to "Shorter" and you'll see that the data on the right edge of the chart is displayed incorrectly. 

I've tested it with smaller data sets, and don't see the issue: https://codepen.io/dcavins/pen/XWdoQKM

Thanks again!

**Comment by Denyllon** [comment]
Hi @dcavins ,

Thank you for contacting us, and apologize you've been waiting so long.
The problem you described above is not directly related with wrapper, but Highcharts itself though. It can be reproduced without Vue, what you can see here: https://jsfiddle.net/BlackLabel/watzm9u7/

Actually, in order to make the problem disappear in your example, you need to do a one small thing. It's caused by the fact that the column series has the `cropThreshold` property set by default to 50, so you just need to increase it, let's say, to the number of your points or more.

Here is the example: https://jsfiddle.net/BlackLabel/s3jynx06/
API Reference: https://api.highcharts.com/highcharts/series.column.cropThreshold

Kind regards!

**Comment by dcavins** [comment]
Thanks very much for looking into this and providing the property I needed to know about. I appreciate that you took the time to share your expertise.
