### ISSUE TITLE
how to toggle theme if i support dark theme without refreshing the chat

### ISSUE THREAD

**Issue by hemanth-sp** [highcharts/highcharts-vue#164]

**Comment by Denyllon** [comment]
Hi @hemanth-sp ,

Could you provide me with more detailed info about what do you want to achieve? Unfortunately I do not quite understand what you meant.

Kind regards!

**Comment by hemanth-sp** [comment]
in my project, I am supporting the dark mode, so how to toggle the theme of the chart light to Dracula and Dracula to light?

**Comment by Denyllon** [comment]
Unfortunately there is no straightforward way to change the chart appearance from one theme to another, because almost all of Highcharts official themes are adding the options which was set by default into the chart config on init. In this case you need to manually find the options which aren't set initially, and set them into your own 'default' setup.
If you will set your own style definitions, then just need to call `Highcharts.setOptions()` method on every theme toggle action, and pass the theme object into that function.
The last thing you need to do is to add some flag within your component data, and assign it as the `:key` value of your chart component. Then it will re-render always when the flag will change.

Live demo: https://codesandbox.io/s/highcharts-vue-demo-forked-es179

Hope it will help,
Kind regards!
