### ISSUE TITLE
Styled Scrollbar doesn't work

### ISSUE THREAD

**Issue by Avasse** [highcharts/highcharts-vue#166]
Hi everyone,

I tried to use the stylizable scrollbar as described in this doc : 
https://www.highcharts.com/demo/stock/styled-scrollbar

With thtat configuration : 
```chartOptions: {
          ...chartOptions,
          scrollbar: {
            barBackgroundColor: 'red',
            barBorderRadius: 7,
            barBorderWidth: 0,
            buttonBackgroundColor: 'red',
            buttonBorderWidth: 0,
            buttonBorderRadius: 7,
            trackBackgroundColor: 'none',
            trackBorderWidth: 1,
            trackBorderRadius: 8,
            trackBorderColor: '#CCC'
          },
          series: [],
          xAxis: {
            type: "category",
            max: this.maxWidthItems,
            scrollbar: {
              enabled: true
            },
          },
          plotOptions: {
            series: {
              cursor: 'pointer',
              events: {
                click: event => {
                  this.onGraphColClick({ sid: event.point.sid })
                }
              }
            }
          },
        }`
```

But the scrollbar didn't change. Is there something i'm doing wrong ? 

Thanks for your repplies :)

**Comment by Denyllon** [comment]
Hi @Avasse ,

Thank you for your report.
It's hard to guess how your app is implemented exactly, and what could cause the issue, but here is the demo which shows the styling works fine: https://codesandbox.io/s/highcharts-vue-demo-forked-hhfet
If it won't help you to resolve your issue, please provide me with the minimal example, where the problem occurs, so that I would be able to inspect it.

Kind regards!

**Comment by Denyllon** [comment]
Closed due to inactivity.
