### ISSUE TITLE
Dynamic X and Y axis

### ISSUE THREAD

**Issue by sjoris** [highcharts/highcharts-vue#17]
Hi,

I'm trying to dynamically add a Y axis to the chartOptions object, but I keep getting errors.
Dynamically creating series works (if there is already an existing X and Y axis in the chartOptions from the start).

I created a sandbox: [codesandbox.io](https://codesandbox.io/s/50233v4qy4) which shows the problem I'm having.
In **src/components/Chart.vue** is the code. I gave every new axis it's own ID and inserted it with:
`this.chartOptions.yAxis.push(newAxis);`
In this sandbox, every new series is added to the highest X and Y axis.
(if you remove the ID of the axis, the push method will run into an infinite loop, strange)

Maybe I'm adding the axis in a wrong way. In the DEMO app was no example of dynamically adding series or axis.

Kind regards

**Comment by Denyllon** [comment]
hi @sjoris,

First, sorry for little bit of late with the answer (holidays).
Your problem occurs not because of `highcharts-vue` wrapper, but the Vue framework itself, and the `Observer` object placed in computed properties. If you would log the `length` of your component data (xAxis, yAxis objects), then you would see the length value is always greater by 1 than it should be in real, so that's why your app is breaking.
I suggest you to check the `length` of Chart object `xAxis` and `yAxis` arrays, by this way:
```js
    addSeries() {
      this.counter;
      var newSeries = {
        name: "test " + this.counter,
        data: [
          [1531814400000, 10 * Math.random()],
          [1531814880000, 10 * Math.random()],
          [1531815360000, 10 * Math.random()],
          [1531815840000, 10 * Math.random()],
          [1531816320000, 10 * Math.random()],
          [1531816800000, 10 * Math.random()],
          [1531817280000, 10 * Math.random()],
          [1531817760000, 10 * Math.random()],
          [1531818240000, 10 * Math.random()],
          [1531818720000, 10 * Math.random()]
        ],
        xAxis: this.$children[0].chart.xAxis.length - 1,
        yAxis: this.$children[0].chart.yAxis.length - 1
      };
      // console.log('serie: ', newSeries)
      this.chartOptions.series.push(newSeries);

      // console.log('chartOptions: ', this.chartOptions)
    },
```

Live example: https://codesandbox.io/s/v3y0p25r10

Kind regards!

**Comment by sjoris** [comment]
Hi @Denyllon,

Tnx for your reply. No problem for the late answer, we all need a good Holiday.
Your answer fixed my problem, thanks a lot!
