### ISSUE TITLE
HIghcharts has no default export

### ISSUE THREAD

**Issue by drfbwilliams** [highcharts/highcharts-vue#173]
Hi - I'm trying to install for a React solution and having tried several variations, I still cant get Highcharts to resolve with an error stating that Highcharts has no default export.

HighchartsReact from highcharts-react-official is fine though.

If this is a known issue, can you let me know which version to roll back to if possible.

Cheers

**Comment by Denyllon** [comment]
Hi @drfbwilliams ,

Thank you for contacting us, and reporting this issue, but I suspect that is not the exact place where you wanted to open this issue, because it's repository of `highcharts-vue` package though.
I recommend you to ask your question on the React official wrapper, where the guys should help you to resolve your React related problems. Here is the link: https://github.com/highcharts/highcharts-react

Kind regards!
