### ISSUE TITLE
Points maintain marker properties after the marker property has been removed

### ISSUE THREAD

**Issue by GreenLoofa** [highcharts/highcharts-vue#177]
This is most easily shown in the following codesandbox:
https://codesandbox.io/s/highcharts-vue-demo-forked-3sxg5?fontsize=14&hidenavigation=1&theme=dark

In the linked sandbox, only the first point and the last point in the series should be red, as they are the only points with the `marker` property. As points are added, the existing points lose the `marker` property, yet the points still remain red in the chart.

**Comment by Denyllon** [comment]
Hi @GreenLoofa 

Thank you for reporting the issue.
It seems that is totally expected behaviour of the Highcharts library. As this wrapper uses the `Highcharts.update()` method under the hood, a whole configuration object is passed into the mentioned update function every time it's needed, and it only updates existing points with the new values/configs. Just to be clear, once you set the marker's options like `color`, `width` or `visibile`, then they will be set up until explicitly turn them off by updating existing points.

In order to make it work as you want, just need to extend your `mounted()` lifecycle hook so that it will also update the marker state for not boundary points. Here is the code snippet:

```js
  mounted() {
    console.log("Mounted");
    var x = 0;
    setInterval(
      function () {
        console.log("new data");
        this.chartData.push({ x: x, y: 5, marker: { enabled: false } });
        x++;
      }.bind(this),
      3000
    );
  },
```
Live example: https://codesandbox.io/s/highcharts-vue-demo-forked-4ptik

Kind regards!
