### ISSUE TITLE
how to use drilldown?

### ISSUE THREAD

**Issue by xingdouchen** [highcharts/highcharts-vue#178]
how to use highmaps drilldown? and the data/mapdata will be request with axios;
just like https://jshare.com.cn/highmaps/hhhhvb, but it is not vue demo.
are there anyone can give me a vue demo?thanks~

**Comment by Denyllon** [comment]
Hi @xingdouchen ,

Thank you for opening the issue.
Actually, it is not bug report, so you should better ask your question on one of official Highcharts support channels (Forum, StackOverflow, via email to support@highcharts.com).

Despite the fact the demo you provided us with is not working at all, exceptionally, I took a look on it and found what is happening, so will try to explain the problem here.

The mentioned demo is loading scripts "on the fly" using the `$.getScript()`, which is not a good practice in context of Vue (and every other) framework, because it directly tries to influence on the dom tree, and load the scripts globally. 
Definitely better approach here would be to send request for the `geo.json` equivalent of map file, and assign it manually to the `Highcharts.maps` list.

I've also created the demo which is working perfectly, so please take a look on it.

Live example: https://codesandbox.io/s/highcharts-vue-demo-forked-qum2j

Kind regards!
