### ISSUE TITLE
Charts events are not being fired upon redefining of chart options

### ISSUE THREAD

**Issue by OverDriveGain** [highcharts/highcharts-vue#182]
Redefining the options for **highcharts** component as the code in the [sandbox](https://codesandbox.io/s/pensive-pascal-1yblz?file=/src/App.vue) doesn't let the chart events trigger properly. However if the options of the highcharts component were initiated including the events. Like this:

`
data: () => ({
    highChartOptions: {
      chart: {
        events: {
          selection(event) {
            console.log('test');
          },
        },
        zoomType: 'x',
      },
    },
  }),
`

Then everything works as expected. Is it a highchart bug, or wrapping error?. Or isn't it a bug at all?

**Comment by Denyllon** [comment]
Hi @OverDriveGain ,

Sorry for not giving you any feedback for so long. It looks like the problem is reproducible in Highcharts natively, so after reviewing its reported issues, I found the perfect match (please take a look [here](https://github.com/highcharts/highcharts/issues/6538)). There you can find a couple of workarounds which should help you to avoid the problem. If you would have any further questions, feel free to let me know about them.

Kind regards!
