### ISSUE TITLE
chart.scrollablePlotArea not showing scroll in Nuxt.js

### ISSUE THREAD

**Issue by MaxPowerReforged** [highcharts/highcharts-vue#187]
Hi! I am trying to get a wide chart to be responsive on mobile. I tried using chart.scrollablePlotArea with minWidth, but the chart stays bigger than its container, and the scrollbar doesn't appear.

I'll try to provide a sample as soon as possible, thanks!

**Comment by Denyllon** [comment]
Hi @MaxPowerReforged 

Thank you for contacting us.
You're right, that would be great to take a look on the real example of the problem, because I produced the demo with scrollable plot area, and it works like a charm.
Here is it: https://codesandbox.io/s/highcharts-vue-demo-forked-ev4fe

It might be even much easier to you to reproduce the issue basing on that demo, so feel free to start from this point.

Kind regards!

**Comment by MaxPowerReforged** [comment]
Hi! Thanks for taking the time to make a sandbox and help :)
I created a minimal Sandbox using Nuxt.js and the same configuration for the chart that you provided. The problem seems to be related to the type of chart: Using "spline" works great, however when I change to "line", the scroll area stops working:
https://codesandbox.io/s/magical-hugle-xrb5e?file=/pages/index.vue
