### ISSUE TITLE
tilemap err：TypeError: Cannot read property 'colorPointMixin' of undefined

### ISSUE THREAD

**Issue by zouliuyun** [highcharts/highcharts-vue#194]
**use  tilemap err**

error info：

> TypeError: Cannot read property 'colorPointMixin' of undefined
>     at tilemap.js:11
>     at k (tilemap.js:10)
>     at tilemap.js:10
>     at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/datav/tilemapChart.vue?vue&type=script&lang=js& (tilemapChart.vue:17)
>     at __webpack_require__ (bootstrap:768)
>     at fn (bootstrap:129)
>     at Module../src/components/datav/tilemapChart.vue?vue&type=script&lang=js& (tilemapChart.vue?8efa:1)
>     at __webpack_require__ (bootstrap:768)
>     at fn (bootstrap:129)
>     at Module../src/components/datav/tilemapChart.vue (tilemapChart.vue:1)

version info：
```
"vue": "^2.5.17",
"highcharts": "^9.1.2",
"vue2-highcharts": "^1.2.5",
```
highcharts less 6.2.0 is ok

code info：https://codesandbox.io/embed/vue-highcharts-demo-forked-iwosm?fontsize=14&hidenavigation=1&theme=dark

**Comment by Denyllon** [comment]
Hi @zouliuyun ,

Thank you for contacting us.
As I see, you're running the `vue2-highcharts` package which is not our official wrapper, and as a result, we're not providing support services related to this package. Please try to use our official package (its name in NPM is `highcharts-vue`), and then contact us in case of any problems.

Kind regards!

**Comment by zouliuyun** [comment]
@Denyllon 
Thank you for give me propose.
I use  highcharts-vue replace  vue2-highcharts，it doesn‘t work

code url ：
https://codesandbox.io/s/vue-highcharts-demo-forked-iwosm?from-embed=&file=/src/components/3DChart.vue

**Comment by Denyllon** [comment]
There are two problems of why your code does not work correctly.

The main reason of why the tile map shows the error is this module requires Highmaps to run, what you can read about within [Highcharts documentation](https://www.highcharts.com/docs/chart-and-series-types/tilemap-series#how-to-create-a-tilemap), and what you can deduce after taking a look on the code in every single one example of tile map from their demo page. After replacing the import of `highcharts` to `highcharta/highmaps`, the error disappears.

Well, that's not all, and after the problem with color point mixin error, we've got another problem, and the charts don't show up at all, and that's because you're trying to register the component in a wrong way.
Your `import` statements of Highcharts Vue package are importing a whole package, instead of importing a standalone component. Here is the docs, where you can read about the way of using this wrapper: 

- https://github.com/highcharts/highcharts-vue#registering-globally-as-a-plugin
- https://github.com/highcharts/highcharts-vue#registering-locally-in-your-component

I've just repaired your example, and did all things needed to make it work correctly (I hope).
Here you're: https://codesandbox.io/s/vue-highcharts-demo-forked-h87x6

Remember that here, we're solving the **issues** related to the Vue wrapper, and all Highcharts support questions shall be 
directed to a certain support channel, like Highcharts Forum, StackOverflow, or directly on support@highcharts.com.

Kind regards!

**Comment by zouliuyun** [comment]
@Denyllon 
Problem has been solved
thank you very much
