### ISSUE TITLE
calling setExtremes does nothing

### ISSUE THREAD

**Issue by Martin-Eckleben** [highcharts/highcharts-vue#201]
Hi highcharts-vue team,

first and foremost let me thank you for your work!

In this stackblitz im trying to set the extremes on button click.
It does not work although everything seems correct to me ( I oriented myself with this issue #83).

https://stackblitz.com/edit/vuejs-starter-mj7ca4?file=highcharts-test.component.js

If I comment in the min/max in the config object the min/max are respected.

If I´m not doing anything obviously stupid already I might be free to look more into it.

highcharts 9.3.1
highcharts-vue 1.4.0
vue 2.6.14

**Comment by Denyllon** [comment]
Hi @Martin-Eckleben ,

Thank you for opening the issue!
Basically, this issue is not related with our wrapper itself, but with native Highcharts, as we can produce [the same effect](https://jsfiddle.net/5tg0o4eh/) without using this package. Furthermore, in case of any support questions, you should contact Highcharts support team via one of available channels (forum, StackOverflow, email to support@highcharts.com)

Anyway, it looks like one thing you need to do is to override the default `xAxis.minRange` value, e.g by setting it equal to `1`, and it'll start to work as intended.

Here is the demo: https://stackblitz.com/edit/vuejs-starter-pqtdyo
API Reference: https://api.highcharts.com/highcharts/xAxis.minRange

Hope it helped!
Kind regards.
