### ISSUE TITLE
Changing drilldown series data dynamicly does not work

### ISSUE THREAD

**Issue by HarisHashim** [highcharts/highcharts-vue#21]
I have code that change chartOption series and drilldown dynamicly. Series work but drilldown does not work.

I have import your demo code in codesandbox to demonstrate this issue. Basicly I just change the first chart component that allow series to be changed dynamicly by filling up numbers into inputbox. 

My change is to apply the same points to a working drilldown in chart Option.

Before that dynamic change happen, drilldown is working. After putting any number into the input box, it stop working.

Appreciate it if you can have a look at bellow url

EDIT: Wow! CodeSandbox is so not user friendly. I make some changes to your demo code. Tested to be working but then what? I have no way to save it to my sandbox and share the url here. I can only paste some picture.

Both codes in src\components\chart.vue

![screenshot_20180823-194956](https://user-images.githubusercontent.com/1856131/44523976-79399e00-a70e-11e8-974a-790853e038ef.jpg)

![screenshot_20180823-195029](https://user-images.githubusercontent.com/1856131/44523989-8191d900-a70e-11e8-8b0f-2ecef2429605.jpg)

**Comment by HarisHashim** [comment]
Create a new [sandbox](https://codesandbox.io/s/lx2yy532y9)!

**Comment by Denyllon** [comment]
Thank you for reporting the issue.
Unfortunately, it's not a bug at all and that's only the effect of incorrect way of implementation, so I'll try to explain you **why** it's happening.

First of all, you defined the `data` parameter inside of your series just like that:
```js
series: [{
    data: [{y:10, drilldown:'first'}, {y:0, drilldown:'second'}, 8, 2, 6, 4, 5, 5],
    color: '#6fcd98'
}],
```
So, on first chart render, your drilldowns works fine, but let's try to deduce what happening if you're trying to change any number in `input` field.
There is the `watch` function assigned to `points` component data element (which is actually an array of numbers), and it assigns the `newValue` to the `chartOptions.series[0].data`, so basically at this level of process you can see what is happening with your initially set data. It has been overridden by new data value without `drilldown` field.
In order to fix that, first you need change the definition of `points` component field, so that it would be an array of objects, and then change the way of modeling the data, just like that:
```js
points: [{y:10, drilldown: 'first'}, {y:0, drilldown: 'second'}, {y:8}, {y:2}, {y:6}, {y:4}, {y:5}, {y:5}],
```

```html
        <form class="row points">
          <div v-for="index in 8" :key="index">
            <p>{{index}}</p>
            <input v-model.number="points[index-1].y" type="number" class="numberInput">
          </div>
        </form>
```
Here is working example: https://codesandbox.io/s/r0vw6mk80m

Hope it helps you.

Kind regards!

**Comment by HarisHashim** [comment]
Thanks and you are right!
