### ISSUE TITLE
Using Boxplots

### ISSUE THREAD

**Issue by andreas-groos** [highcharts/highcharts-vue#22]
Seeing that `highcharts-more` is deprecated and I can't find boxplots etc under /modules, how do I include this functionality?

Thanks

**Comment by Denyllon** [comment]
Additionally, here is the example which shows how to `import` and use mentioned module.
https://codesandbox.io/s/rl7p5n1x9m

**Comment by andreas-groos** [comment]
Thanks

**Comment by t2wu** [comment]
@Denyllon The demo link is dead. Is there another? I am struggling with BoxPlot at the moment.

**Comment by KacperMadej** [comment]
@t2wu 
The idea is rather simple as I have explained in my previous comment, but if you have any problems please create a live demo I could debug it. 

P.S. Denyllon will be back in office next week if you want to wait.

**Comment by Denyllon** [comment]
Hello @t2wu ,

As Kacper said in the last comment, it's very easy to import required Highcharts module in your project, what you can read in the documentation's [Importing Highcharts Modules](https://github.com/highcharts/highcharts-vue#importing-highcharts-modules) section.

If it's not clear enough to you, then please take a look on the following example of importing and using `highcharts-more` module.

Live example: https://codesandbox.io/s/highcharts-vue-demo-mec3b

Kind regards!

**Comment by bmckay959** [comment]
I'm struggling with this same issue using box plots. I have tried importing highcharts-more, but it's saying that it is deprecated. I know this issue is old, but I've been working on this for 2 days and no luck.

Error:
https://assets.highcharts.com/errors/17/?missingModuleFor=boxplot

<img width="1011" alt="Screenshot 2023-08-17 at 7 10 57 PM" src="https://github.com/highcharts/highcharts-vue/assets/7681836/4496c23d-4d28-4f05-a88a-6f530085e93a">

When trying to import module/boxplot, it is not available either. I'm using highcharts-vue. You can see the IDE is not finding the autocomplete either.

<img width="938" alt="Screenshot 2023-08-17 at 7 12 48 PM" src="https://github.com/highcharts/highcharts-vue/assets/7681836/65556234-5c3c-46e9-8dee-09e72ae61a5e">

Any suggestions on what I'm missing?

**Comment by jakubSzuminski** [comment]
Hi @bmckay959,

1. You do not have to install another package (`highcharts-more`). Installing `highcharts` is completely enough as you can import all the necessary modules from there.
2. As you can see in this [demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/audio-boxplot) the `highcharts-more.js` file is not in the `/modules` directory, but is on the same level as `highcharts.js` file.

Here's a **demo** showing how to use `boxplot` in `highcharts-vue`: https://codesandbox.io/s/keen-wildflower-r6z5cc?file=/src/main.js
