### ISSUE TITLE
no demos for the Sankey Chart

### ISSUE THREAD

**Issue by fzc-seaside-villager** [highcharts/highcharts-vue#232]
Hi, recently I'm trying to add a Sankey chart to my project via the highcharts-vue wrapper. But I could not find an official demo in the guide.

If a demo for the Sankey chart could be added, it would be great for users of the highcharts-vue wrapper and make it a better guide.

Looking forward to the improvement.

Thank you.

**Comment by jakubSzuminski** [comment]
Hi, thanks!

You can take a look at our official Vanilla JS sankey demo here: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/sankey-diagram

This works nearly the same for Highcharts with Vue so in order to create a Sankey Chart you need to import `modules/sankey` (https://api.highcharts.com/highcharts/series.sankey).

You have it explained in this section of readme: https://github.com/highcharts/highcharts-vue#importing-highcharts-modules

Here's a **demo** of a sankey chart with Highcharts-Vue: https://codesandbox.io/s/highcharts-vue-demo-forked-fxsjq2

Let me know if that helps!

**Comment by jakubSzuminski** [comment]
Closing as not planned.

**Comment by fzc-seaside-villager** [comment]
Thank you very much!

Yea, I think it will help many highcharts-vue users including me :p
