### ISSUE TITLE
Highchart inside Bootstrap Modal

### ISSUE THREAD

**Issue by droplister** [highcharts/highcharts-vue#31]
I've seen other people with this issue, but the fixes I've seen don't work for me.

Essentially, I want to set a max-width on the chart. I tried applying a `style="max-width"` to the component, but that ends up setting the width, not a max-width. I've tried doing...

```
        chart: {
          events: {
            load() {
              setTimeout(this.reflow.bind(this))
            }
          }
        },
```

How would I call reflow outside of this event definition? Say, when the open modal button was pressed? 

You can see what I'm talking about on at this URL by clicking "Forecast" in green in the top right: http://moon.bitcorns.com/harvests/1. I am getting this issue on Google Chrome. 

![bitcorn harvest 1 bitcorn crops](https://user-images.githubusercontent.com/8001717/45795050-a161e180-bc67-11e8-8171-0baf6a441d8f.png)

**Comment by Denyllon** [comment]
Thank you for your report.

Unfortunately, I'm not able to reproduce the described issue on my Chrome (v69.0.3497.92) and OSX (v10.13). Could you tell me which Chrome version and what operating system you have? Actually, it's a bit hard to debug your app, because the code is bundled and minified.

Kind regards!
