### ISSUE TITLE
Having an issue with implementing the package -

### ISSUE THREAD

**Issue by GeorgeZoum** [highcharts/highcharts-vue#34]
Does anyone have another example of an active Vue or Vuetify project that has an active HighCharts chart in it? It would be helpful to see it in a project to see what I am doing wrong, or how to improve the current project that I have. 
Thank you

**Comment by Denyllon** [comment]
Appreciate you contacting us.

The **Issues** is our tracker for all bugs related to this wrapper. Your issue is actually the question for our support team, so next time would be great if you would use one of the support channels (forum, Stack Overflow platform, direct email to support@highcharts.com).

To see the demo example with dynamic Highcharts implementation, please refer to the [Demo app](https://github.com/highcharts/highcharts-vue#demo-app) section in the wrapper documentation, or run this live demo: https://codesandbox.io/s/n3o2ypkzx0

Best regards!
