### ISSUE TITLE
why "addpoint" is not a function  in highcharts-vue

### ISSUE THREAD

**Issue by Penguin-Lin** [highcharts/highcharts-vue#35]
![image](https://user-images.githubusercontent.com/33897969/47058442-a4fd6f80-d1f7-11e8-97e7-875827c42aaa.png)

var series = this.chartOptions.series[0]
setInterval(function () {
                    var x = (new Date()).getTime(), // 当前时间
                          y = Math.random()         // 随机值
                    series.addPoint({x, y}, true, true)
                }, 1000)

**Comment by Denyllon** [comment]
Hi @Penguin-Lin 

Thank you for your report. I assume, that you're trying to call `addPoint()` function on the `series` object within the component data, right? Basically, it will not be possible, because it's just standard JavaScript Object, which hasn't got the `Series.prototype` functions. 

If you would like to add point to your data, just use `Array.push()` function, to push new values into your component data. The wrapper is watching changes on options, so it will automaticaly update the chart if needed. For example:

```html
<template>
  <div>
    <highcharts :options="chartOptions" :updateArgs="updateArgs"></highcharts>
    <button @click="addPoint">Add Point</button>
  </div>  
</template>
```
```js
<script>
export default {
  data() {
    return {
      counter: 0,
      chartOptions: {
        series: [
          {
            data: [1,2,0]
          }
        ]
      },
      updateArgs: [true, true, { duration: 1000 }]
    };
  },
 methods: {
   addPoint() {
     this.chartOptions.series[0].data.push(5)
   }
 }
};
</script>
```

**Live example:** https://codesandbox.io/s/zkvp88zq4

Best regards!

**Comment by shadyabhi** [comment]
Hi @Denyllon ,

Why are the chart options not reactive? By that, what I mean is, if I use a "data from component" value for chartOptions.series[0].data, the chart fails to render. 

Example: https://codesandbox.io/s/383461vv7m

**Comment by zavodptica** [comment]
Hi @shadyabhi , you must initialize all root-level reactive data properties upfront, even with an empty value. [https://codesandbox.io/s/mor8m74p0y](https://codesandbox.io/s/mor8m74p0y)

**Comment by shadyabhi** [comment]
Hi @zavodptica, thanks for replying. 

Line 16 in Chart.vue: https://codesandbox.io/s/mor8m74p0y That's not empty value. 
In my use-case, the data is received via API call, hence I would like to bind it to a `data()` in vuejs and then let the reactive nature of vuejs to do the magic. Is that not possible?

**Comment by Denyllon** [comment]
Hi @shadyabhi,

The problem is, that you're trying to refer `this.dataArray` in your components data, but actually it it's not returned yet. That way of implementatin is not consistent with Vue conceptions. Please refer to #11 issue, where you will find the solution for your problem.

Kind regards!

**Comment by shadyabhi** [comment]
Hey @Denyllon , thanks a lot for taking time in answering the doubt. 

Would it be nice to update README with this info as I feel that this information is very important to know how this package is used for a newbie.

Thanks

**Comment by Denyllon** [comment]
Hi @shadyabhi ,

We didn't put that information in our documentation, because it directly concerns the Vue framework, JavaScript and their general conceptions of use, so the described problem doesn't lie in a wrong usage of wrapper at all. Could you tell me, why it should be described in the package documentation?

Best regards!

**Comment by Denyllon** [comment]
Hello @Penguin-Lin ,

Could you tell me how exactly you trying to add the new data to your chart? The best way to solve issues related with animation is by using `computed` properties. here is the example of how it should be implemented: https://codesandbox.io/s/m35wxvqx8

Vue API Reference: https://vuejs.org/v2/guide/computed.html

Kind regards!

**Comment by Penguin-Lin** [comment]
Hello, @Denyllon. Thanks for replying. I have already fixed that. Thank you very much.

**Comment by Penguin-Lin** [comment]
![image](https://user-images.githubusercontent.com/33897969/54495800-36e1e380-4922-11e9-9d50-be62f7fa0d92.png)
Hi @Denyllon ,
Can you tell me where to set the tooltip on the X axis? It looks like a tooltip, but it doesn't.
I can't find this property in the API. Thanks.

**Comment by pawelfus** [comment]
Hi @Penguin-Lin - it's [`tooltip.split`](https://api.highcharts.com/highcharts/tooltip.split) option.
