### ISSUE TITLE
Why afterSetExtremes () twice on load events？

### ISSUE THREAD

**Issue by 35n139e** [highcharts/highcharts-vue#39]
I tried setExtremes () and afterSetExtremes () on this sample.
http://jsfiddle.net/DktpS/85/

Why afterSetExtremes () twice on load,
Is setExtremes (), afterSetExtremes () called twice at zoom event?
https://jsfiddle.net/tw96vL2d/

However Your demo did not happen the above.
What's the difference?

**Comment by Denyllon** [comment]
Thank you for your report!

First time `afterSetExtremes` is triggered by `update()` method, which is called from `options` Vue watcher function.
Second one triggers because of updating the chart with "new" event definitions. I wrote "new" in quotation marks for a reason, because actually sending the event definitions through `update()` function adds another functions to previous ones, so then if some event is triggered, all functions are called to.
This problem looks like directly related with https://github.com/highcharts/highcharts/issues/6943 issue, so please refer to that topic.

Kind regards!
