### ISSUE TITLE
afterSetExtremes function called with setExtremes event

### ISSUE THREAD

**Issue by alexyar88** [highcharts/highcharts-vue#41]
afterSetExtremes function called multiple times on navigator mousemove with setExtremes event. There is no way to detect start/end of navigator change. 

And afterSetExtremes doesn't call at all if `navigator.adaptToUpdatedData = false;`

**Comment by Denyllon** [comment]
Hi @alexyar88,

Could you try to reproduce the described problem, and provide me with live example where it occurs? Also, please describe the problem more detailed, because it's hard to deduce what you mean exactly.
Have you tried to exclude the wrapper? I'm asking because the problem could be directly related with Highcharts.

Best regards!

**Comment by Denyllon** [comment]
Closing the issue, due to lack of activity. Please reopen it in case of any further questions.
