### ISSUE TITLE
Organization chart

### ISSUE THREAD

**Issue by verilog15** [highcharts/highcharts-vue#42]
I was wondering if its possible to create an organization chart with this project?
Something similar to the following chart:
image

![image](https://user-images.githubusercontent.com/39248005/48510612-09463a00-e85d-11e8-96e8-4b8c84ff2a00.png)
 
If the answer is yes, where can I see an example or a demo?
Thank you

**Comment by Denyllon** [comment]
Hi @verilog15 ,

This project is only the wrapper for Highcharts library, so that question should be asked on one of the Highccharts support channels (Highcharts forum, Stack overflow, or support@highcharts.com). Unfortunately, Highcharts doesn't have the organization chart type, but you can use `SVGRenderer` to generate what you need. Here is the example: https://www.highcharts.com/demo/renderer. I also recommend you to look into the API: https://api.highcharts.com/class-reference/Highcharts.SVGRenderer

Kind regards!
