### ISSUE TITLE
Default vue.js config does not understand worldmap.js

### ISSUE THREAD

**Issue by ramonakira** [highcharts/highcharts-vue#43]
Hi, 

I'm using the default setup generated with Vue CLI 3 of VueJS and while trying your example I ran into an issue with the worldmap.js-file:

I got the error:

```"export 'default' (imported as 'addWorldMap') was not found in './js/worldmap.js'```

I fixed it by changing the worldmap.js to:

```export const worldmap = {'title': 'World, Miller projection, medium resolution', ...```

and in the main.js import it as such:

```
import {worldmap} from './js/worldmap'
```

and then load it to the corresponding map as such:

```
Highcharts.maps['myMapName'] = worldmap
```

I don't know if this is the proper way, but it works!

Maybe it would be an idea to update this example to use the default VueJS setup?

**Comment by Denyllon** [comment]
Hi @ramonakira ,

Thank you for your report. The problem occurs, because the `worldmap.js` file is the `UMD` module type, and it doesn't have the `default` export, but the Vue CLI bundler (most probably) requires, that all modules should be written using ES module syntax.

_Internal note:
There should be more detailed description about using external maps in projects based on wrapper.
_

Best regards!
