### ISSUE TITLE
How can I specify or set the highcharts object in this wrapper ? 

### ISSUE THREAD

**Issue by code4jhon** [highcharts/highcharts-vue#56]
So I'm working on a Vue application that is going to be deployed in a standalone mode but it's also going to be embedded in another application (an ExtJs app) however the ExtJs app already loads Highcharts and that is generating errors, is there a way I can specify the highcharts-vue wrapper to use a specific Highcharts instance? 

e.g

```
     Vue.use(VueHighcharts, {
        Highcharts: H
      })
```

**Comment by code4jhon** [comment]
Looking at the source code seems that's not supported. 

I'll be happy to collaborate/contribute with this if some direction is provided.

**Comment by Denyllon** [comment]
Hi @code4jhon ,

This Vue wrapper has the `Highcharts` package defined as `peerDepedency`, so user need to care about importing that library himself. Other packages should automatically use the same instance of Highcharts because `npm` should care about it. If there is more than one instance of Highcharts created on your application, then the error should be thrown in console.
Currently, wrapper doesn't have such feature which gives ability to indicate specific instance of Highcharts on which the charts are generated, because we assume its not supported to load more instances.

Kind regards!

**Comment by code4jhon** [comment]
I understand the problem is that the project where I'm embedding my Vue app is not loading Highcharts as a node module, and since this plugin doesn't look for window.Highcharts then the plugin is actually not working. On the other hand if I do include Highcharts in my Vue project as a node module then I get an error because Highcharts is already defined. I know this is an edge case but it would be very cool to be able to set the Highcharts instance to be used. Like in this plugin https://github.com/weizhenye/vue-highcharts

Using that plugin the dev can do something like this:

```
let H

if (H === undefined) {
      if (window['Highcharts'] !== undefined) {
        H = window['Highcharts']
      } else {
        H = require('highcharts')

        window['Highcharts'] = H

        require('highcharts/modules/exporting')(H)
        require('highcharts/modules/map')(H)
        require('highcharts/modules/export-data')(H)
        require('./vendor/highcharts/patches')
      }

      Vue.use(VueHighcharts, {
        Highcharts: H
      })
    }
```

**Comment by code4jhon** [comment]
So we have managed to use the other plugin successfully but I want to move to the official wrapper :)

**Comment by pawelfus** [comment]
Just a word of explanation regarding on this part:
> On the other hand if I do include Highcharts in my Vue project as a node module then I get an error because Highcharts is already defined.

In the next Highcharts release (v7.0.4) we will stop throwing error about loading Highcharts multiple times (error 16). That means you will be able to use different versions of Highcharts, for example one loaded as node module and another one through `<script>` tag.

**Comment by code4jhon** [comment]
Awesome!!! Thanks for the heads up :)

**Comment by code4jhon** [comment]
Hmmm but that would mean I'd have to load higcharts twice : / 

If we were able to set the instance then we would be able to load it only once.

**Comment by pawelfus** [comment]
Yes, of course, if you need **the same** version of Highcharts, then loading library twice is redundant - solution you mentioned above is a good idea IMHO. I was only referring to the part about error, sorry for the confusion! 

Alternatively, if Highcharts are not injected, just check `window.Highcharts` in the wrapper. Still, a direct setter for Highcharts instance could be the best solution.

**Comment by code4jhon** [comment]
Got you, thank you very much for your replies 👍

**Comment by pawelfus** [comment]
Let's reopen the issue and let @Denyllon decide what is the best solution here. Thanks for your feedback!  👍

**Comment by code4jhon** [comment]
Ok great! Thank you very much.

**Comment by Denyllon** [comment]
I avoided adding possibility to pass a specific Highcharts instance while registering the wrapper as a plugin, because I wanted to make it easier to use, a bit more user friendly, and automatic (less definitions and code), but due to the fact that upcoming version will stop throwing mentioned error, and there would be possible and supported to use more than one Highcharts instance, however, the best solution would be to extend the wrapped with that feature.

I still don't have idea, why current solution would produce any errors, because even if you're not running this wrapper using `npm`, it checks whether the Highcharts is available on global scope. Please take a look on this example: https://jsfiddle.net/BlackLabel/ukc2kqnb/.

**Comment by code4jhon** [comment]
Not sure if I understood correctly, are you saying that if I do `Vue.use(HighchartsVue.default)` then it should look for the Highcharts object in the global scope ? 

But if I do `Vue.use(HighchartsVue)` then  it would expect it's peer dependency to be there ?

If that's the case then great! That does sound to be very flexible and should cover pretty much all scenarios (including my use case). 

However doing something like: 
```
if (window['Highcharts'] !== undefined) {
  Vue.use(HighchartsVue.default)
} else {
  Vue.use(HighchartsVue)
}
```

throws `Uncaught TypeError: Cannot read property 'install' of undefined` 

This happens when my vue app files are loaded dynamically (before I actually start using the vue components)

**Comment by Denyllon** [comment]
Not really. Both of them uses the Highcharts available on global scope, but if you refers to `HighchartsVue.default`, then you'll receive the function based on `install` function template provided by Vue, about which you can read in Vue documentation here: https://vuejs.org/v2/guide/plugins.html#Writing-a-Plugin
In case of refering `HighchartsVue`, then you're getting a whole object with the `install` function and pure `Chart` component.

At this moment there is no any other way of doing it, because Highcharts object have to be available on global scope, and it is not possible to pass specific Highcharts instance.

Best regards!

**Comment by code4jhon** [comment]
Got you, thanks 👍

**Comment by Denyllon** [comment]
Indicating a specific Highcharts instance added since v1.3.0. Closing the issue.
