### ISSUE TITLE
When using boost, console gives me an error: Uncaught TypeError: Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by MehrdadKhanzadeh** [highcharts/highcharts-vue#57]
Hey! I'm trying to use boost library for faster speed in my large data set. There's not a proper documentation for using it, after searching a lot I found out that I have to use it this way:

```
import Vue from 'vue'
import HighchartsVue from 'highcharts-vue'
import boost from 'highcharts/modules/boost'
Vue.use(HighchartsVue)
boost(HighchartsVue)
```
But I have this error in console:
```
Uncaught TypeError: Cannot read property 'document' of undefined
    at eval (boost.js?d817:44)
    at eval (boost.js?d817:64)
    at eval (main.js?cebd:11)
    at Module../src/renderer/main.js (renderer.js:1325)
    at __webpack_require__ (renderer.js:725)
    at fn (renderer.js:102)
    at Object.0 (renderer.js:1396)
    at __webpack_require__ (renderer.js:725)
    at renderer.js:792
    at renderer.js:795
```
And nothings renders in my page! I'm using electron, with Chrome 61. What should I do? Thanks!

**Comment by Denyllon** [comment]
Hello @MehrdadKhanzadeh 

Thank you for contacting us.
Actually, you defined it in a wrong way, because you're passing the `HighchartsVue` object as the argument of `boost()` module when loading the boost module, but there should be passed the Highcharts library instance, not a wrapper. You can read more about it on [Importing Highcharts modules](https://github.com/highcharts/highcharts-vue#importing-highcharts-modules) documentation section of this wrapper.
I produced the example, which shows how exactly it should be configured, so please take a look on it.

Live example: https://codesandbox.io/s/v7w4mppj3

Best regards!
