### ISSUE TITLE
Map does not support latitude/longitude

### ISSUE THREAD

**Issue by MohanadI** [highcharts/highcharts-vue#63]
Is there any solution to use lat/lng ? 

I need some thing like this https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/mappoint-latlon/

I am using world map https://jsfiddle.net/gh/get/library/pure/highslide-software/highcharts.com/tree/master/samples/mapdata/custom/world-continents

and I got this error www.highcharts.com/errors/22

**Comment by Denyllon** [comment]
Hi @MohanadI ,

Thank you for reporting the issue.
Actually, in order to make the `lat` and `lon` parameters to work, you have to import the [proj4.js](https://proj4.org/) 3rd-party library, what is mentioned in our Highcharts [documentation](https://www.highcharts.com/docs/maps/latlon):
> This feature requires that the proj4js library has been loaded before Highmaps.

Please install the `proj4.js` library, import it and assign to a window object like below:

```
window.proj4 = proj4;
```

Kind regards!
