### ISSUE TITLE
Using Plugins

### ISSUE THREAD

**Issue by jim-moore-sp** [highcharts/highcharts-vue#66]
Could you extend the demo app to demonstrate using a plugin? I am unable to get even a simple plugin as described on https://www.highcharts.com/docs/extending-highcharts working:

(function (H) {
     var localVar,         // local variable
     Series = H.Series; // shortcut to Highcharts prototype
     console.log('hello world');
}(Highcharts));

Trying to run this with highcharts-vue results in the error: "Uncaught ReferenceError: Highcharts is not defined"

**Comment by Denyllon** [comment]
Hi @jim-moore-sp 

This error occurs because you didn't import the Highcharts at all. The only requirement is to have installed `highcharts` npm package in application where the wrapper is used. If you would like to extend Highcharts, first you need to import the library somewhere in your code (for example in main file of application). I prepared the example which shows how to extend Highcharts within Vue project, so please refer to it.

Live example: https://codesandbox.io/s/vmyn6n2jjl

Kind regards!

**Comment by hounded** [comment]
Hi man, any chance how I would use this plugin ? 
https://github.com/streamlinesocial/highcharts-regression
I have tried 

```javascript
import regression from 'highcharts-regression'
import HighchartsVue from 'highcharts-vue'
import Highcharts from 'highcharts'

regression(Highcharts)
Vue.use(HighchartsVue)

```

**Comment by Denyllon** [comment]
Hi @hounded ,

I assume that you are running some old version of the package, and that is why the plugin doesn't work correctly. Please update the `highcharts-vue` package to the latest version (at now v1.3.4), and then try to use it again.

Here is the example: https://codesandbox.io/s/highcharts-vue-demo-dsfo4

Kind regards!

**Comment by chuckienorton** [comment]
Thanks @Denyllon. I know this thread is old, but the above messages seemed so relevant i thought I would add here instead of creating a new thread. Same issue, same console error. If you prefer me creating a new issue, lmk.  

I'm trying to use the [multicolor_series](https://github.com/blacklabel/multicolor_series) plugin to generate [colored segments](https://jsfiddle.net/chuckienorton/spkv5qax/3/). Here is my code: 

import App from './App.vue';
const app = createApp(App);

```
import Highcharts from 'highcharts';
import HighchartsMulticolorSeries from "highcharts-multicolor-series";
import HighchartsVue from 'highcharts-vue';

HighchartsMulticolorSeries(Highcharts);
app.use(HighchartsVue);
```

The error is 'Uncaught ReferenceError: Highcharts is not defined' 

Package versions: 
```
"highcharts": "^9.1.2",
"highcharts-multicolor-series": "^2.4.0",
"highcharts-vue": "^1.4.0",
```

Thanks in advance!

**Comment by chuckienorton** [comment]
> Hi! You're right.
> ...
> You can deal with this in 2 ways:
> 
> 1. You could either create a type declarations file for the module (you can read more about it here: https://medium.com/@steveruiz/using-a-javascript-library-without-type-declarations-in-a-typescript-project-3643490015f3)
> 2. Or figure out a workaround without using this plugin (depending on your needs); for this, if you encounter any problems, do not hesitate to ask on our forum: https://www.highcharts.com/forum/ - we'll be happy to help!
> ...

Ok thanks @jakubSzuminski  - our project is not in TypeScript (I know, sorry). But it sounds like i could possibly fork & modify the plugin to work with our system. I'll look into it and report back. 

Thanks for the quick response!
