### ISSUE TITLE
Chart data of object gets overwritten, but only the first object that is interacted with is affected

### ISSUE THREAD

**Issue by ChadRoberts21** [highcharts/highcharts-vue#67]
Here is this a code sand box proving and showcasing this issue: https://codesandbox.io/embed/ql4rm9734w?fontsize=14

When a user clicks on a button in the app. A widget is meant to show the data of that object. The the object contains an array that is used to produce a graph. The first object's button click seems to display and function correctly. So does the second and the third. But when the first objects button is clicked again the chart data property of the object is overwritten with the chart data of the previously clicked object.

I have tried the following with no luck

- Vue dev tools and debugging, shows the symptoms of the error but does not point to where the error takes place.
- I have tried making the data property a pseudo private property that can only be accessed with setters and getters. The setter is never called.
- Added second property in the class to act as a  unmodified storage variable for the original data given at construction time. This second property also gets modified.
- When examining the store in depth, it looked like the object array in the store was not affected by the bug. However when refactored to use the object from the store directly the bug is still there.
- I tried to separate out the data into a separate state property that is not related to the object in any direct way... still the same bug.
- I also tried with a every small data array (5 elements, original array length between 640-1200 elements) still the bug persisted.
- I have even built a mini replica project in the hopes that at the smallest scale the bug does not appear and hopefully it would be a silly typo or something... but again, even this mini version of my app still shows the bug. the Mini version can be found here: https://github.com/ChadRoberts21/ChartMapBug
- Built a more refined smaller example: https://codesandbox.io/embed/ql4rm9734w?fontsize=14

I expect that the correct chart data is always shown in the object widget and for the object to not have its data property overridden at all unless I expressly choose to do so in a Vuex mutation

**Comment by Denyllon** [comment]
Hi @ChadRoberts21 ,

Thank you for reporting the issue.
We're currently taking a closer look on this case in order to debug what can cause problems like that. It looks like the problem occurs only after Highcharts v7.0.1, so probably it refers directly to native library, but we need to make deeper investigation.
We'll let you know about the progress of this case.

Kind regards!

**Comment by Denyllon** [comment]
Basically, Highcharts mutates a data due to some performance reasons (copying large datasets is very expensive), and that's why the problem occurs. In your example, you always assign the `this.foo.data` as `series.data`, so actually you're just assigning the reference to an array with data each time.

Let's prepare the minified example of what's happening, without using Vue framework:
```html
<script src="https://code.highcharts.com/highcharts.js"></script>

<div id="container"></div>
<button id="setData1">Set first data set</button>
<button id="setData2">Set second data set</button>
```
```js
var data1 = [1,2,3],
  data2 = [3,2,1];

var chart = Highcharts.chart('container', {
    series: [{
        name: 'Installation',
        data: []
    }]
});

setData1.onclick = function() {
    chart.update({
  	series: [{
    	data: data1
    }]
  })
}

setData2.onclick = function() {
    chart.update({
  	series: [{
    	data: data2
    }]
  })
}
```
In the example above, when try to update the chart with first data set, then with second, and again with the first, then the effect will be the same as on your application. The data will be mutated because of fact that just the reference to an array is passed through the `update()` function.
Under the hood, Highcharts calls the `series.setData()` function, which just replace the elements of old array with new ones, and that's why both arrays have the same values after calling a few different updates.

In order to avoid that behaviour, just need to pass elements of data array as new array of elements, for example using ES6 spread operator:

```js
setData1.onclick = function() {
    chart.update({
  	series: [{
    	data: [...data1]
    }]
  })
}
```

In order to make your application work correctly, please use spread operator within the `FooWidget.vue` component file, when you assigning the new series data.


Minified example: https://jsfiddle.net/BlackLabel/uk3mxn5p/
Minified example (with spread): https://jsfiddle.net/BlackLabel/36qaLf8g/

Fixed Vue example: https://codesandbox.io/s/w2wyx88vxl

Kind regards!
