### ISSUE TITLE
<script> option suggested in sample code does not work with different CDN

### ISSUE THREAD

**Issue by gopala000** [highcharts/highcharts-vue#69]
I updated the CDN to https://cdn.jsdelivr.net/npm/highcharts-vue@1.2.0/dist/module/highcharts-vue.min.js in your sample code https://jsfiddle.net/BlackLabel/ukc2kqnb/ and ran the code. It failed with various javaScript error. I'd like to use the approach outlined in the sample code but use different CDN because the one used in sample is in end of life.  Please suggest a workaround.

**Comment by Denyllon** [comment]
Hello @gopala000 ,

Thank you for report.
It happens because jsdelivr.net platform directly shares the module file, instead of script-tag one. Both files should be merged into one in upcoming wrapper version, but since it will come, you can just assign the `Highcharts` global variable to a new `highcharts` variable, right after script tag with library.

```html
<script src="https://code.highcharts.com/highcharts.js"></script>
<script>
highcharts = Highcharts
</script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/highcharts-vue@1.2.0/dist/module/highcharts-vue.js"></script>
```

It's because the library is available on global scope but its name is different (without capital letter).

Here is the example: https://jsfiddle.net/BlackLabel/ghckboym/

Kind regards!

**Comment by gopala000** [comment]
That worked! Thanks for the quick response.

**Comment by Denyllon** [comment]
Builds are now (since v.1.3.0) merged into one unified file. Closing the issue.
