### ISSUE TITLE
render wrong when change radar to funnel

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts-vue#93]
**when i change he type from radar to funnel,the funnel charts render like this picture**

![222222222222222222222](https://user-images.githubusercontent.com/6789138/61115847-fb1cec00-a4c5-11e9-89c4-9072722a7db7.png)

![1111111111111111111111](https://user-images.githubusercontent.com/6789138/61115384-eb50d800-a4c4-11e9-9c12-333ef74487d8.png)
**radar code**
`
chart: {
            polar: true,
           type: 'line'
        },
        yAxis: {
            gridLineInterpolation: 'polygon',
            lineWidth: 0,
            min: 0,
            gridLineWidth: 1
        },
        xAxis: {
            tickmarkPlacement: 'on',
            lineWidth: 0,
            gridLineWidth: 1
        }
`

**funnel code**
`chart: {
            polar: false,
            type: 'funnel'
        },
        yAxis: {
            gridLineInterpolation: null,
            lineWidth: 0,
            min: 0,
            gridLineWidth: 1
        },
        xAxis: {
            tickmarkPlacement:null,
            lineWidth: 0,
            gridLineWidth: 1
        }
`

**Comment by Denyllon** [comment]
Hi @wjhcc2018 ,

Thank you for contacting us.
Actually, the problem stems from the fact, that both series types have the different `series.clip` settings, and when you're trying to update them in this way (only  changing the type), then the `clip` value is not changing at all, so that's why funnel series does not update its `clip-path` parameter value.

If you would like to make it works correctly, just need to pass changed `series.clip` value equal `true` while updating, or just set it on init like it is done in the following example.

**Live example:** https://jsfiddle.net/BlackLabel/L2gjbopk/

_By the way, that issue should be reported on https://github.com/highcharts/highcharts repository, instead of this one, so next time would be better to check whether the problem is not with a native Highcharts package._
